# Generated by Django 2.1.5 on 2019-02-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Franchise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('franchise_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Glace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parfum_text', models.CharField(max_length=50)),
                ('parfum_id', models.IntegerField(default=0)),
                ('poids', models.FloatField(default=0)),
                ('date_prod', models.DateField(verbose_name='date de production')),
                ('location', models.CharField(default='Labo', max_length=100)),
                ('status', models.CharField(default='Disponible', max_length=20)),
                ('franchise_name', models.CharField(default='None', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Parfum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parfum_text', models.CharField(max_length=50)),
            ],
        ),
    ]
