# Generated by Django 2.1.5 on 2019-02-21 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AjaxTest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='glace',
            name='commande_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
