# Generated by Django 2.1.5 on 2019-02-21 10:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AjaxTest', '0002_glace_commande_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glace',
            name='commande_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 21, 11, 35, 20, 478998)),
        ),
    ]
