# Generated by Django 2.1.2 on 2019-02-28 21:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AjaxTest', '0003_auto_20190221_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='glace',
            name='no_lot',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='glace',
            name='commande_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 28, 22, 46, 32, 387917)),
        ),
    ]
