# Generated by Django 2.1.2 on 2019-03-03 15:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AjaxTest', '0004_auto_20190228_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glace',
            name='commande_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 3, 16, 21, 19, 637748)),
        ),
        migrations.AlterField(
            model_name='glace',
            name='no_lot',
            field=models.CharField(max_length=50),
        ),
    ]
