# Generated by Django 2.1.2 on 2019-03-03 15:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AjaxTest', '0005_auto_20190303_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glace',
            name='commande_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 3, 16, 24, 39, 245922)),
        ),
    ]
