# Generated by Django 2.1.2 on 2019-03-14 19:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AjaxTest', '0006_auto_20190303_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glace',
            name='commande_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 14, 20, 40, 54, 477766)),
        ),
    ]
